<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2021-07-06 00:44:42 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/frontend/default/course_page.php 122
ERROR - 2021-07-06 00:44:42 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/frontend/default/course_page.php 212
ERROR - 2021-07-06 07:32:29 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/frontend/default/course_page.php 129
ERROR - 2021-07-06 07:32:29 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/frontend/default/course_page.php 219
ERROR - 2021-07-06 07:34:31 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/frontend/default/course_page.php 129
ERROR - 2021-07-06 07:34:31 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/frontend/default/course_page.php 219
ERROR - 2021-07-06 09:08:16 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 09:08:16 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 09:17:23 --> Severity: Warning --> date() expects parameter 2 to be integer, string given /var/www/html/application/views/backend/admin/offline_payment.php 93
ERROR - 2021-07-06 09:17:23 --> Severity: Warning --> date() expects parameter 2 to be integer, string given /var/www/html/application/views/backend/admin/offline_payment.php 98
ERROR - 2021-07-06 09:18:41 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/frontend/default/my_courses.php 52
ERROR - 2021-07-06 09:18:41 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/frontend/default/my_courses.php 210
ERROR - 2021-07-06 09:24:57 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 09:24:57 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 09:25:18 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 09:25:18 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 09:39:34 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 09:39:34 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 09:52:22 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/controllers/Home.php 275
ERROR - 2021-07-06 10:07:12 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:07:12 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:15:53 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:15:53 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:19:35 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:19:35 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:24:09 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:24:09 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:25:24 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:25:24 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:25:59 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:25:59 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:27:13 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:27:13 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:28:18 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:28:18 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 10:59:05 --> Severity: error --> Exception: syntax error, unexpected '$batch_id' (T_VARIABLE), expecting ',' or ')' /var/www/html/application/views/backend/admin/schedule_add.php 19
ERROR - 2021-07-06 10:59:15 --> Severity: error --> Exception: syntax error, unexpected '$batch_id' (T_VARIABLE), expecting ',' or ')' /var/www/html/application/views/backend/admin/schedule_add.php 19
ERROR - 2021-07-06 10:59:40 --> Severity: error --> Exception: syntax error, unexpected '$batch_id' (T_VARIABLE), expecting ',' or ')' /var/www/html/application/views/backend/admin/schedule_add.php 19
ERROR - 2021-07-06 11:00:59 --> Severity: error --> Exception: syntax error, unexpected '$batch_id' (T_VARIABLE), expecting ',' or ')' /var/www/html/application/views/backend/admin/schedule_add.php 19
ERROR - 2021-07-06 11:01:02 --> Severity: error --> Exception: syntax error, unexpected '$batch_id' (T_VARIABLE), expecting ',' or ')' /var/www/html/application/views/backend/admin/schedule_add.php 19
ERROR - 2021-07-06 11:01:10 --> Severity: error --> Exception: syntax error, unexpected '$batch_id' (T_VARIABLE), expecting ',' or ')' /var/www/html/application/views/backend/admin/schedule_add.php 19
ERROR - 2021-07-06 11:01:21 --> Severity: error --> Exception: syntax error, unexpected '$batch_id' (T_VARIABLE), expecting ',' or ')' /var/www/html/application/views/backend/admin/schedule_add.php 19
ERROR - 2021-07-06 11:23:19 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:23:19 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:26:31 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:26:31 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:28:47 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:28:47 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:29:07 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:29:07 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:30:02 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:30:02 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:30:07 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:30:07 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:32:01 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:32:01 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:33:56 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:33:56 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:34:01 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:34:01 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:35:07 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:35:07 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:35:18 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:35:18 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:36:29 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:36:29 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:36:34 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:36:34 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:37:58 --> Severity: error --> Exception: syntax error, unexpected end of file /var/www/html/application/views/backend/admin/schedule_edit.php 160
ERROR - 2021-07-06 11:38:04 --> Severity: error --> Exception: syntax error, unexpected end of file /var/www/html/application/views/backend/admin/schedule_edit.php 160
ERROR - 2021-07-06 11:38:06 --> Severity: error --> Exception: syntax error, unexpected end of file /var/www/html/application/views/backend/admin/schedule_edit.php 160
ERROR - 2021-07-06 11:38:09 --> Severity: error --> Exception: syntax error, unexpected end of file /var/www/html/application/views/backend/admin/schedule_edit.php 160
ERROR - 2021-07-06 11:38:55 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:38:55 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:39:03 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:39:03 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:39:08 --> Severity: Warning --> Use of undefined constant batch_details - assumed 'batch_details' (this will throw an Error in a future version of PHP) /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 11:39:08 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/backend/admin/schedule_edit.php 71
ERROR - 2021-07-06 12:48:00 --> Query error: Column 'batch_id' cannot be null - Invalid query: INSERT INTO `batch_schedules` (`title`, `start_date`, `start_time`, `duration`, `timezone`, `meeting_id`, `status`, `password`, `join_url`, `host_id`, `batch_id`, `course_id`, `created_at`, `updated_at`, `meeting_detail`) VALUES ('Schedule 1www', 1626825600, 1625590800, '60', 'Asia/Kolkata', '83162031480', 'confirmed', '886371', 'https://us02web.zoom.us/j/83162031480?pwd=bUg5cjhHYUcydFZMZG56NmdBRlZ6dz09', '1', NULL, NULL, 1625529600, 1625529600, '{\"start_url\":\"https:\\/\\/us02web.zoom.us\\/j\\/83162031480?pwd=bUg5cjhHYUcydFZMZG56NmdBRlZ6dz09\",\"join_url\":\"https:\\/\\/us02web.zoom.us\\/j\\/83162031480?pwd=bUg5cjhHYUcydFZMZG56NmdBRlZ6dz09\",\"password\":\"886371\",\"timezone\":\"Asia\\/Kolkata\"}')
ERROR - 2021-07-06 12:48:10 --> Query error: Column 'batch_id' cannot be null - Invalid query: INSERT INTO `batch_schedules` (`title`, `start_date`, `start_time`, `duration`, `timezone`, `meeting_id`, `status`, `password`, `join_url`, `host_id`, `batch_id`, `course_id`, `created_at`, `updated_at`, `meeting_detail`) VALUES ('Schedule 1qqq', 1627257600, 1625590800, '60', 'Asia/Kolkata', '83162031480', 'confirmed', '886371', 'https://us02web.zoom.us/j/83162031480?pwd=bUg5cjhHYUcydFZMZG56NmdBRlZ6dz09', '1', NULL, NULL, 1625529600, 1625529600, '{\"start_url\":\"https:\\/\\/us02web.zoom.us\\/j\\/83162031480?pwd=bUg5cjhHYUcydFZMZG56NmdBRlZ6dz09\",\"join_url\":\"https:\\/\\/us02web.zoom.us\\/j\\/83162031480?pwd=bUg5cjhHYUcydFZMZG56NmdBRlZ6dz09\",\"password\":\"886371\",\"timezone\":\"Asia\\/Kolkata\"}')
ERROR - 2021-07-06 15:54:57 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/frontend/default/course_page.php 129
ERROR - 2021-07-06 15:54:57 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/application/views/frontend/default/course_page.php 219
